### ISSUE TITLE
type_hints and fit not consistent

### ISSUE THREAD

**Issue by williamwongys** [dabl/dabl#130] opened 2019-12-07 15:49 UTC
When I use type_hints in clean to correct the types identified wrongly by the detect_types, the resulted correct types are not used in subsequent fit. 

`hint['field1']='continuous'`
`input_clean,types = dabl.clean(new_input, return_types=True,type_hints=hints)`
...
`fc = dabl.SimpleClassifier(random_state=0)`
`fc.fit(input_clean, target_col='y') #here the corrected type is not used`

I checked the source code:
`def _fit(self, X, y=None, target_col=None):`
...
`types = detect_types(X)`
...
`sp = EasyPreprocessor(verbose=verbose, types=types)`

so the problem is the new correct types were never used in the preprocessing.

So the fit function should somehow accept the return_types as parameter.

**Comment by amueller** [comment] 2019-12-10 00:27
Thank you for the issue. That's indeed not ideal. The problem is that right now, EasyPreprocessor doesn't know if the data has been cleaned already.
I'm not entirely sure how to encode that while staying within standard pandas.
We could use custom dtypes to signal that cleaning has already happened, but that seems quite heavy-handed.
For now, the models should probably accept type hints and you'd need to pass them in for each step (or the types provided by clean).

If you have other suggestions on how to solve this I'm happy to hear them.

A somewhat orthogonal issue: if you could provide the data or a synthetic example of the data that was not correctly detected, we could try to improve type detection. Though we can't really assume it to be always correct.

I'm at NeurIPS this week so I might not be able to respond quickly.

**Comment by williamwongys** [comment] 2019-12-11 14:20
Yes, the model should accept type hints or the types provided by clean. I don't think you could perfect clean because ordinal category should be determined by users and there is no way algorithm could tell ordinal from nominal category.

I tried to add the type_hints parameter in SimpleClassifier.fit(), it worked ok but when I tried to add type_hints to AnyClassified.fit(), I got the following exception:

ValueError: Pipeline.fit does not accept the types parameter. You can pass parameters to specific steps of your pipeline using the stepname__parameter format, e.g. `Pipeline.fit(X, y, logisticregression__sample_weight=sample_weight)`.

Is there a quick fix?

**Comment by amueller** [comment] 2019-12-11 17:56
How did you pass ``type_hints`` to SimpleClassifier.fit? There's currently no support for that.

I'm not sure if I want the type hints in ``fit``, I think the more scikit-learn-like API would be passing them in ``__init__``.

The fix is to add these as arguments to the classifiers. It's quite easy but I'm at NeurIPS right now and don't have a lot of time for coding.
Feel free to send a PR, otherwise I'll try to do it towards the weekend.

**Comment by amueller** [comment] 2019-12-14 00:49
This is fixed in master now. Please let me know if that works for you.

**Closed as completed** 2019-12-14 00:48 UTC
